version: '3.8'
services:
  airflow:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: airflow_w2 
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor #tipe executor yang digunakan
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DB_URI}
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY} #enskripsi informasi sensitif di airflow
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=${AIRFLOW_WWW_USER_USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_WWW_USER_PASSWORD}
    depends_on:
      - airflow_metadata
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-networks

  airflow_metadata:
    image: postgres:latest
    container_name: airflow_metadata
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    ports:
      - 5440:5432
    volumes:
      - airflow_metadata:/var/lib/postgresql/data
    networks:
      - airflow-networks

  data_source_pactravel:
    image: postgres:latest
    container_name: data_source_pactravel
    environment:
      POSTGRES_USER: ${SRC_USER}
      POSTGRES_PASSWORD: ${SRC_PASSWORD}
      POSTGRES_DB: ${SRC_DB_NAME}
    ports:
      - 5441:5432
    networks:
      - airflow-networks
    volumes:
      - ./src:/docker-entrypoint-initdb.d 
      - data_source_pactravel:/var/lib/postgresql/data

  dwh_pactravel:
    image: postgres:latest
    container_name: dwh_pactravel
    environment:
      POSTGRES_USER: ${DWH_USER}
      POSTGRES_PASSWORD: ${DWH_PASSWORD}
      POSTGRES_DB: ${DWH_DB_NAME}
    ports:
      - 5442:5432
    networks:
      - airflow-networks
    volumes:
      - ./dwh:/docker-entrypoint-initdb.d
      - dwh_pactravel:/var/lib/postgresql/data


  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - airflow-networks

volumes:
  airflow_metadata:
    driver: local
    name: airflow_metadata

  dwh_pactravel:
    driver: local
    name: dwh_pactravel

  minio-data:
    driver: local
    name: minio-data

  data_source_pactravel:
    driver: local
    name: data_source_pactravel

networks:
  airflow-networks:
    driver: bridge
    name: airflow-networks